"""Artifacts and logs page."""

from __future__ import annotations

from pathlib import Path

try:
    from ui.bootstrap import ensure_repo_root_on_path
except ModuleNotFoundError:
    import sys

    _UI_DIR = Path(__file__).resolve().parents[1]
    _UI_DIR_TEXT = str(_UI_DIR)
    if _UI_DIR_TEXT not in sys.path:
        sys.path.insert(0, _UI_DIR_TEXT)
    from bootstrap import ensure_repo_root_on_path

ensure_repo_root_on_path(__file__)

import streamlit as st

from ui.pages.common import preview_artifact, render_export_note, render_markdown_block, render_page_intro, render_section_stack, render_table


def render(state: dict, ui_state: dict) -> None:
    export_mode = bool(ui_state.get("export_mode"))
    render_page_intro(
        "Artifacts / Logs / Registries",
        "This page exposes the synced reproducibility indexes, manifest inventory, final case registry, and log inventory in a read-only way. Panel-friendly mode stays high-level; advanced mode allows direct artifact preview and download.",
        badge="Read-only artifact browser",
    )

    if export_mode:
        render_export_note(
            [
                "Export mode keeps this page high-level and sequential so the PDF captures the main registries without interactive previews.",
                "Artifact previews and log inspection stay available only in the live read-only dashboard.",
            ]
        )

    catalog = state["final_output_catalog"]
    case_registry = state["final_case_registry"]
    manifests = state["final_manifest_index"]
    logs = state["final_log_index"]

    def _case_registry() -> None:
        render_table(
            "Final case registry",
            case_registry,
            download_name="final_case_registry.csv",
            caption="This registry exposes the main workflow lanes and their authoritative curated package roots.",
            height=280,
            max_rows=None if ui_state["advanced"] else 20,
            export_mode=export_mode,
        )
        if ui_state["advanced"] and not export_mode and not case_registry.empty:
            selected = st.selectbox(
                "Preview primary output root",
                case_registry["primary_output_root"].astype(str).tolist(),
                key="case_root_preview",
            )
            preview_artifact(selected)

    def _output_catalog() -> None:
        render_table(
            "Final output catalog",
            catalog,
            download_name="final_output_catalog.csv",
            caption="This catalog is regenerated by the Phase 5 sync and is the safest way to see what artifact groups exist right now.",
            height=320,
            max_rows=None if ui_state["advanced"] else 40,
            export_mode=export_mode,
        )
        if ui_state["advanced"] and not export_mode and not catalog.empty:
            selected = st.selectbox("Preview output artifact", catalog["relative_path"].astype(str).tolist(), key="catalog_preview")
            preview_artifact(selected)

    def _manifest_index() -> None:
        render_table(
            "Final manifest index",
            manifests,
            download_name="final_manifest_index.csv",
            caption="Manifest inventory pulled from the synced final reproducibility package.",
            height=320,
            max_rows=None if ui_state["advanced"] else 40,
            export_mode=export_mode,
        )
        if ui_state["advanced"] and not export_mode and not manifests.empty:
            selected = st.selectbox("Preview manifest", manifests["relative_path"].astype(str).tolist(), key="manifest_preview")
            preview_artifact(selected)

    def _log_index() -> None:
        render_table(
            "Final log index",
            logs,
            download_name="final_log_index.csv",
            caption="Log preview stays read-only. Missing optional logs are tolerated.",
            height=260,
            max_rows=None if ui_state["advanced"] else 30,
            export_mode=export_mode,
        )
        if ui_state["advanced"] and not export_mode and not logs.empty:
            selected = st.selectbox("Preview log", logs["relative_path"].astype(str).tolist(), key="log_preview")
            preview_artifact(selected)

    def _package_notes() -> None:
        render_markdown_block("Final reproducibility summary", state["final_reproducibility_summary"], collapsed=True, export_mode=export_mode)
        render_markdown_block("Publication captions", state["publication_captions"], collapsed=True, export_mode=export_mode)
        render_markdown_block("Publication talking points", state["publication_talking_points"], collapsed=True, export_mode=export_mode)

    render_section_stack(
        [
            ("Case registry", _case_registry),
            ("Output catalog", _output_catalog),
            ("Manifest index", _manifest_index),
            ("Log index", _log_index),
            ("Package notes", _package_notes),
        ],
        export_mode=export_mode,
    )
