"""Artifacts and logs page."""

from __future__ import annotations

from pathlib import Path

try:
    from ui.bootstrap import ensure_repo_root_on_path
except ModuleNotFoundError:
    import sys

    _UI_DIR = Path(__file__).resolve().parents[1]
    _UI_DIR_TEXT = str(_UI_DIR)
    if _UI_DIR_TEXT not in sys.path:
        sys.path.insert(0, _UI_DIR_TEXT)
    from bootstrap import ensure_repo_root_on_path

ensure_repo_root_on_path(__file__)

import streamlit as st

from ui.pages.common import preview_artifact, render_export_note, render_markdown_block, render_metric_row, render_page_intro, render_section_stack, render_table


def render(state: dict, ui_state: dict) -> None:
    export_mode = bool(ui_state.get("export_mode"))
    render_page_intro(
        "Artifacts / Logs / Registries",
        "This is the reference page for synced reproducibility indexes, panel-result verification outputs, the paper-to-output registry, manifest inventory, final case registry, and log inventory. Panel-friendly mode stays high-level; advanced mode allows direct artifact preview and download.",
        badge="Reference page | read-only registries",
    )

    if export_mode:
        render_export_note(
            [
                "Export mode keeps this page high-level and sequential so the PDF captures the main registries without interactive previews.",
                "Artifact previews and log inspection stay available only in the live read-only dashboard.",
            ]
        )

    catalog = state["final_output_catalog"]
    case_registry = state["final_case_registry"]
    manifests = state["final_manifest_index"]
    logs = state["final_log_index"]
    panel_review_check = state["panel_review_check_table"]

    def _package_overview() -> None:
        render_metric_row(
            [
                ("Case registry rows", str(len(case_registry))),
                ("Output catalog rows", str(len(catalog))),
                ("Manifest index rows", str(len(manifests))),
                ("Log index rows", str(len(logs))),
            ],
            export_mode=export_mode,
        )
        st.info("Panel-friendly mode keeps raw artifact, manifest, and log previews out of the main story. Switch to Advanced for direct read-only inspection.")

    def _panel_review() -> None:
        render_table(
            "Panel review result check",
            panel_review_check,
            download_name="panel_results_match_check.csv",
            caption="When present, this table shows the latest read-only manuscript-to-output verification written to output/panel_review_check/.",
            height=280,
            max_rows=None if ui_state["advanced"] else 25,
            export_mode=export_mode,
        )
        render_markdown_block(
            "Paper-to-output registry",
            state["paper_output_registry_markdown"],
            collapsed=not ui_state["advanced"],
            export_mode=export_mode,
        )
        render_markdown_block(
            "Panel review report",
            state["panel_review_check_markdown"],
            collapsed=True,
            export_mode=export_mode,
        )
        if ui_state["advanced"] and not export_mode:
            preview_options = [
                "docs/PAPER_OUTPUT_REGISTRY.md",
                "output/panel_review_check/panel_results_match_check.md",
                "output/panel_review_check/panel_review_manifest.json",
            ]
            selected = st.selectbox("Preview panel artifact", preview_options, key="panel_artifact_preview")
            preview_artifact(selected)

    def _case_registry() -> None:
        render_table(
            "Final case registry",
            case_registry,
            download_name="final_case_registry.csv",
            caption="This registry exposes the main workflow lanes and their authoritative curated package roots.",
            height=280,
            max_rows=None if ui_state["advanced"] else 20,
            export_mode=export_mode,
        )
        if ui_state["advanced"] and not export_mode and not case_registry.empty:
            selected = st.selectbox(
                "Preview primary output root",
                case_registry["primary_output_root"].astype(str).tolist(),
                key="case_root_preview",
            )
            preview_artifact(selected)

    def _output_catalog() -> None:
        render_table(
            "Final output catalog",
            catalog,
            download_name="final_output_catalog.csv",
            caption="This catalog is regenerated by the Phase 5 sync and is the safest way to see what artifact groups exist right now.",
            height=320,
            max_rows=None if ui_state["advanced"] else 40,
            export_mode=export_mode,
        )
        if ui_state["advanced"] and not export_mode and not catalog.empty:
            selected = st.selectbox("Preview output artifact", catalog["relative_path"].astype(str).tolist(), key="catalog_preview")
            preview_artifact(selected)

    def _manifest_index() -> None:
        render_table(
            "Final manifest index",
            manifests,
            download_name="final_manifest_index.csv",
            caption="Manifest inventory pulled from the synced final reproducibility package.",
            height=320,
            max_rows=None if ui_state["advanced"] else 40,
            export_mode=export_mode,
        )
        if ui_state["advanced"] and not export_mode and not manifests.empty:
            selected = st.selectbox("Preview manifest", manifests["relative_path"].astype(str).tolist(), key="manifest_preview")
            preview_artifact(selected)

    def _log_index() -> None:
        render_table(
            "Final log index",
            logs,
            download_name="final_log_index.csv",
            caption="Log preview stays read-only. Missing optional logs are tolerated.",
            height=260,
            max_rows=None if ui_state["advanced"] else 30,
            export_mode=export_mode,
        )
        if ui_state["advanced"] and not export_mode and not logs.empty:
            selected = st.selectbox("Preview log", logs["relative_path"].astype(str).tolist(), key="log_preview")
            preview_artifact(selected)

    def _package_notes() -> None:
        render_markdown_block("Final reproducibility summary", state["final_reproducibility_summary"], collapsed=True, export_mode=export_mode)
        render_markdown_block("Publication captions", state["publication_captions"], collapsed=True, export_mode=export_mode)
        render_markdown_block("Publication talking points", state["publication_talking_points"], collapsed=True, export_mode=export_mode)

    sections = [
        ("Package overview", _package_overview),
        ("Panel review", _panel_review),
        ("Case registry", _case_registry),
        ("Package notes", _package_notes),
    ]
    if ui_state["advanced"] and not export_mode:
        sections[3:3] = [
            ("Output catalog", _output_catalog),
            ("Manifest index", _manifest_index),
            ("Log index", _log_index),
        ]

    render_section_stack(
        sections,
        export_mode=export_mode,
        use_tabs=ui_state["advanced"],
    )
